"use client";
import { createContext, useContext, useState, ReactNode, useEffect } from "react";

// Translation dictionaries
const translations = {
  en: {
    home: "Home",
    contactUs: "Contact us",
    cancel: "Cancel",
    reschedule: "Reschedule",
    myTrips: "My trips",
    loginSignUp: "Login",
    myProfile: "My profile",
    logout: "Logout",
    contact: "Contact",
    english: "English",
    kannada: "Kannada",
    quickLinks: "Quick Links",
    travelNow: "Travel Now",
    aboutUs: "About us",
    login: "Login",
    informationCenter: "Information Center",
    termsConditions: "Terms & Conditions",
    faqs: "FAQS",
    stayConnected: "Stay Connected",
    reachUs: "Reach us out here",
    copyright: "©2025 Nandhu Bus. All Rights Reserved",
    poweredBy: "Powered By Seabed2Crest Technologies Private Limited",
    getInTouch: "Get in touch",
    contactDescription: "We're here to help with any questions or concerns about your bus booking.",
    phoneSupport: "Phone Support",
    supportHoursWeek: "Monday to Saturday, 9am - 6pm",
    email: "Email",
    responseTime: "We'll respond as quickly as possible",
    officeAddress1: "1st floor, RD Rajanna Complex , Rajanukunte,",
    officeAddress2: "Yelahanka Taluk Bengaluru North",
    officeAddress3: "Karnataka - 560064",
    supportHours: "Support Hours",
    weekdayHours: "Monday to Friday: 9am - 8pm",
    saturdayHours: "Saturday: 10am - 6pm",
    sundayHours: "Sunday: Closed",
    followUs: "Follow Us",
    contactForm: "Contact Form",
    supportOptions: "Support Options",
    sendMessage: "Send us a Message",
    name: "Name",
    yourName: "Your name",
    yourEmail: "your@email.com",
    subject: "Subject",
    howCanWeHelp: "How can we help?",
    message: "Message",
    yourMessage: "Your message",
    sending: "Sending...",
    messageSentSuccess: "Message sent successfully",
    messageFailed: "Failed to send message. Please try again.",
    supportTicket: "Open a Support Ticket",
    supportTicketDesc: "Submit a support ticket for detailed assistance",
    scheduleCall: "Schedule a Call",
    scheduleCallDesc: "Book a call with our support team",
    bookingModifications: "Booking Modifications",
    bookingModificationsDesc: "Change or cancel your existing booking",
    emailSupport: "Email Support",
    emailSupportDesc: "Send us an email for non-urgent issues",
    responseTimes: "Expected Response Times",
    phoneResponse: "Phone Support: Immediate to 15 minutes",
    ticketResponse: "Support Tickets: Within 4 hours",
    emailResponse: "Email Enquiries: Within 24 hours",
    termsSubtitle: "From enquiries to Adventures, We're with You",
    termsAcceptanceTitle: "Acceptance of Terms",
    termsAcceptanceContent: "By accessing and using the NandhuBus booking website, you agree to comply with and be bound by the following terms and conditions. If you do not agree with these terms, please do not use this website.",
    termsBookingTitle: "Booking Process",
    termsBookingPoint1: "Users must provide accurate and complete information during the booking process.",
    termsBookingPoint2: "Users are responsible for verifying the accuracy of booking details before confirmation.",
    termsBookingPoint3: "NandhuBus reserves the right to cancel or refuse any booking at its discretion.",
    termsPaymentsTitle: "Payments",
    termsPaymentsPoint1: "Payment for bus bookings must be made through the approved payment methods on the website.",
    termsPaymentsPoint2: "Prices are subject to change without notice, and NandhuBus is not responsible for any discrepancies.",
    termsCancellationsTitle: "Cancellations and Refunds",
    termsCancellationsPoint1: "Cancellation policies vary by route and operator. Users are advised to review the specific cancellation policy associated with their booking.",
    termsCancellationsPoint2: "Refund requests must be made in accordance with the applicable cancellation policy.",
    termsAccountsTitle: "User Accounts",
    termsAccountsPoint1: "Users are responsible for maintaining the confidentiality of their account information and passwords.",
    termsAccountsPoint2: "Users are responsible for all activities that occur under their account.",
    termsPrivacyTitle: "Privacy Policy",
    termsPrivacyContent: "All content on the NandhuBus website, including text, graphics, logos, and images, is the property of NanduBus and is protected by intellectual property laws.",
    termsLiabilityTitle: "Limitation of Liability",
    termsLiabilityContent: "NandhuBus is not liable for any direct, indirect, incidental, special, or consequential damages arising from the use or inability to use the website or services.",
    termsLawTitle: "Governing Law",
    termsLawContent: "These terms and conditions are governed by and construed in accordance with the laws of Indian Jurisdiction.",
    termsFinalNote: "By using the NandhuBus bus booking website, you acknowledge that you have read, understood, and agree to be bound by these terms and conditions. NanduBus reserves the right to modify or update these terms and conditions at any time without prior notice. Users are responsible for regularly reviewing these terms.",
    loginDiscountMessage: "Sign in to avail exciting discounts and cashbacks!!",
    invalidOtp: "Invalid OTP",
    requiredField: "Required",
    invalidOtpTryAgain: "Invalid OTP, please try again.",
    otpSentTo: "OTP sent to",
    enterOtp: "Enter OTP",
    verifying: "Verifying...",
    verifyOtp: "VERIFY OTP",
    otpResentSuccess: "OTP has been resent successfully!",
    changeNumber: "Change Number",
    resendOtp: "Resend OTP",
    invalidPhoneNumber: "Invalid phone number",
    mobileNumber: "Mobile Number",
    enterMobileNumber: "Enter your mobile number",
    generateOtp: "Generate OTP",
    termsAgreement1: "By signing up, you agree to our",
    termsAgreement2: "and",
    privacyPolicy:" Privacy Policy",
    tc:"T&C",
    cu:"Contact",
    mt:"trips",
    welcome:"Welcome!",
    hi:"Hi",
    introduction: "Introduction",
    introductionContent: "This Privacy Policy explains how NandhuBus collects, uses, and protects your information when you use our services.By accessing or using our Service, you agree to the terms outlined below. We are committed to safeguarding your personal data and ensuring transparency in compliance with applicable privacy laws. For questions, contact us at +917090007776/support@nandhubus.com.",
    interpretation: "Interpretation and Definitions",
    interpretationContent: "Terms with initial capitalization have meanings defined under the conditions below. These definitions apply whether the terms appear in singular or plural.",
    definitions: "Definitions",
    registeredAccount: "Registered Account: A personal login credential granting you access to our platform’s features and services.",
    corporateAffiliates: "Corporate Affiliates: Entities that directly or indirectly control, are controlled by, or share common ownership with us, where 'control' means holding at least 50% of voting shares or decision-making authority.",
    businessEntity: "Business Entity: Refers to Seabed2Crest Technologies Private Limited, registered at 1st Floor, R D Rajanna Complex, Rajanukunte, Yelahanka Taluk, Bengaluru, Karnataka, India (560064).",
    browserCookies: "Browser Cookies: Small text files stored on your device when you visit our website, used to enhance functionality and analyze user behavior.",
    governingRegion: "Governing Region: The state of Karnataka, India, whose laws apply to this Privacy Policy.",
    electronicDevice: "Electronic Device: Any hardware equipment (e.g., computers, smartphones, tablets) capable of connecting to and interacting with our services.",
    personalInformation: "Personal Information: Any data that can be used—either alone or combined with other information—to identify a specific individual.",
    digitalServices: "Digital Services: Collectively refers to the Nandhubus online platform, accessible via nandhubus.in.",
    authorizedVendors: "Authorized Vendors: Trusted third-party service providers who assist us in delivering,maintaining, or analyzing our services under strict confidentiality agreements.",
    automatedUsageData: "Automated Usage Data: Information collected passively through your interactions with our services (e.g., session duration, pages visited).",
    endUser : "End User: Any individual or legal entity (e.g., a company) accessing or using our services on their own behalf or others’ behalf.",
    collectingData: "Collecting and Using Your Personal Data",
    typesOfDataCollected: "Types of Data Collected",
    personalData: " While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include: ",
    usageData: " Usage Data is collected automatically when using the Service. This may include your Device's IP address, browser type, browser version, pages visited, visit timestamps, time spent on pages, device identifiers and other diagnostic data. When You access the Service by or through a mobile device, We may collect certain additional information automatically, including, but not limited to: Mobile device type and unique ID,Mobile device IP address, Mobile operating system, Mobile browser type, Mobile device identifiers, Other diagnostic data.",
    trackingTechnologies: "Tracking Technologies and Cookies",
    trackingTechnologiesContent: "We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.",
    cookies: "Cookies or Browser Cookies: A small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.",
    webBeacons: "Small electronic files (clear gifs, pixel tags, single-pixel gifs) that permit the Company to count users who have visited pages, opened an email, and for other related website statistics.",
    necessaryCookies: " Type: Session Cookies. Administered by: Us. Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.",
    cookiesPolicy: "Cookies Policy / Notice Acceptance Cookies: Type: Persistent Cookies. Administered by: Us. Purpose: These Cookies identify if users have accepted the use of cookies on the Website.",
    functionalityCookies: "Functionality Cookies: Type: Persistent Cookies. Administered by: Us. Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.",
    useOfPersonalData: "Use of Your Personal Data",
    useOfPersonalDataContent: "The Company may use Personal Data for the following purposes:",
    serviceProvision: "Service Provision & Maintenance: Ensuring continuous platform operation, Monitoring system performance and usage patterns.",
    accountAdministration: "Account Administration: Facilitating user registration and authentication, Enabling access to platform features and functionalities.",
    contractualObligations: "Contractual Obligations: Executing purchase agreements, Fulfilling service commitments.",
    userCommunications: "User  Communications: Delivering service-related notifications via multiple channels (email, SMS, push notifications), Providing important platform updates and announcements.",
    marketingCommunications: "Marketing Communications: Sharing relevant promotional content about related offerings, Delivering personalized service recommendations.",
    customerSupport: "Customer Support: Addressing user inquiries and service requests, Resolving technical issues and account matters.",
    corporateTransactions: "Corporate Transactions: Facilitating potential mergers, acquisitions, or asset transfers, Supporting due diligence processes.",
    serviceOptimization: "Service Optimization: Conducting data analytics to identify usage trends, Implementing platform improvements and feature enhancements.",
    disclosureCircumstances: "We may disclose your personal information under the following circumstances:",
    thirdPartyServiceProviders: "Third-Party Service Providers: We engage trusted partners to perform essential business functions, including service analytics, performance monitoring, and customer communications, under strict confidentiality agreements.",
    corporateTransactionsDisclosure: "Corporate Transactions: Your information may be transferred as a business asset in the event of mergers, acquisitions, financing, or sale of company assets, with appropriate privacy protections maintained.",
    corporateAffiliatesDisclosure: "Corporate Affiliates: We may share data with entities under common control, all of whom are bound by this Privacy Policy's terms and security standards.",
    strategicPartners: "Strategic Partners: With select business collaborators to provide you with relevant products, services, or promotional offers that may be of interest.",
    publicInteractions: "Public Interactions: Information you voluntarily share in public platform areas may be accessible to other users and potentially redistributed beyond our control.",
    consentBasedDisclosures: "Consent-Based Disclosures: We will obtain explicit permission before sharing your data for any purpose not outlined in this policy.",
    retentionOfData: "Retention of Your Personal Data",
    retentionOfDataContent: "The Company retains your Personal Data only as long as necessary to fulfill the purposes described in this Privacy Policy, including to comply with legal obligations, resolve disputes, enforce agreements, and maintain business records. Usage Data is generally kept for a shorter period unless required to enhance service security, improve functionality, or meet legal requirements. All data retention practices adhere to applicable laws and our internal governance standards.",
    transferOfData: "Transfer of Your Personal Data",
    transferOfDataContent: "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction. Important: Your consent to this Privacy Policy followed by Your submission of information represents Your agreement to that transfer. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.",
    deleteYourData: "Delete Your Personal Data",
    deleteYourDataContent: "You may formally request the permanent removal of your Personal Data from our systems.",
    howToDeleteData: "How to delete your data: 1. Sign in to Your Account if you have one. 2. Visit the account settings section. 3. Select the option to manage your personal information. 4. Follow the instructions to delete your data. Our Service may give You the ability to delete certain information about You from within the Service. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us. Note: We may need to retain certain information when we have a legal obligation or lawful basis to do so.",
    disclosureOfData: "Disclosure of Your Personal Data",
    businessTransactions: "Business Transactions: If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.",
	lawEnforcement: "Law enforcement: Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).",
    otherLegalRequirements: "Other legal requirements: The Company may disclose Your Personal Data in the good faith belief that such action is necessary to: Comply with a legal obligation, Protect and defend the rights or property of the Company, Prevent or investigate possible wrongdoing in connection with the Service, Protect the personal safety of Users of the Service or the public, Protect against legal liability.",
    securityOfData: "Security of Your Personal Data: We implement industry-standard measures to safeguard your Personal Data; however, no electronic transmission or storage system can be guaranteed as completely secure. While we employ commercially reasonable protections, absolute security cannot be assured.",
    paymentsPolicy: "Payments Policy",
    paymentProcessing: "Payment Processing: All payment transactions are securely processed through certified third-party payment processors. We do not collect, store, or process your complete payment card or banking details on our systems. Your payment information is transmitted directly to our authorized payment partners in compliance with PCI-DSS standards, and its handling is governed by the respective processor's privacy and security policies.",
    acceptedPaymentMethods: "Accepted Payment Methods: Credit and debit cards, UPI (Unified Payments Interface), Net banking, Wallets or other digital payment methods. The availability of these methods may vary depending on Your location and the Service being used.",
    paymentSecurity: "Payment Security: Encrypted transactions (HTTPS, SSL/TLS), PCI-DSS compliant processors, Secure payment handling.",
    refundsAndCancellations: "Refunds and Cancellations: Refund and cancellation policies are specific to the Service or product purchased. Please refer to the specific product or service page, or contact Our support team for details regarding: Eligibility for refunds, Timeframe for processing refunds, Conditions for refunds.",
    billingAndCharges: "Billing and Charges: By using our services, you agree to pay all applicable fees and charges, taxes or additional costs imposed by payment processors. Payments must be completed promptly with the billing terms provided. In case of a failed payment or chargeback, we reserve the right to suspend or terminate your access to the services until the issue is resolved.",
    childrensPrivacy: "Children's Privacy",
    importantNotice: "Important Notice: Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers. If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.",
    linksToOtherWebsites: "Links to Other Websites: Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
    changesToPolicy: "Changes to this Privacy Policy: We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. Notification: We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the 'Last updated' date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
    contactUss: "Contact Us: If you have any questions about this Privacy Policy, You can contact us through any of the following methods:",
    terms: "Terms",
    phone: "Phone: +91 7090007776",
    emails: "Email: contact@nandhubus.in",
    blogs:"Blog",
    downloadPolicy: "Download Policy: Click to download PDF",
    soda:"Incredible Journeys, Tailored for You!",
hmm:"Explore More, Spend Less – Adventure Awaits with Our Exclusive Travel Packages!",
cancelandRefund:"Cancellation & Refund Policy",
shippingPolicy:"Shipping Policy",

  },
  kn: {
    home: "ಮುಖಪುಟ",
    contactUs: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    reschedule: "ಮರುನಿಗದಿಪಡಿಸಿ",
    myTrips: "ನನ್ನ ಪ್ರವಾಸಗಳು",
    loginSignUp: "ಲಾಗಿನ್",
    myProfile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    logout: "ಲಾಗ್ ಔಟ್",
    contact: "ಸಂಪರ್ಕ",
    english: "ಇಂಗ್ಲಿಷ್",
    kannada: "ಕನ್ನಡ",
    shippingPolicy:"ಸಾಗಣೆ ನೀತಿ",
    quickLinks: "ದ್ರುತ ಲಿಂಕ್ಗಳು",
    travelNow: "ಈಗ ಪ್ರಯಾಣಿಸಿ",
    aboutUs: "ನಮ್ಮ ಬಗ್ಗೆ",
    login: "ಲಾಗಿನ್",
    blogs: "ಲೇಖನಗಳು",
    informationCenter: "ಮಾಹಿತಿ ಕೇಂದ್ರ",
    termsConditions: "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
    faqs: "ಸಾಮಾನ್ಯ ಪ್ರಶ್ನೆಗಳು",
    stayConnected: "ಸಂಪರ್ಕದಲ್ಲಿರಿ",
    reachUs: "ನಮ್ಮನ್ನು ಇಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ",
    copyright: "©2025 ನಂದು ಬಸ್. ಎಲ್ಲ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲ್ಪಟ್ಟಿವೆ",
    poweredBy: "ಸೀಬೆಡ್2ಕ್ರೆಸ್ಟ್ ಟೆಕ್ನಾಲಜೀಸ್ ನಿಂದ ಶಕ್ತಿಗೊಳಿಸಲಾಗಿದೆ",
    getInTouch: "ಸಂಪರ್ಕಿಸಿ",
    hmm:"  ಇನ್ನಷ್ಟು ಅನ್ವೇಷಿಸಿ, ಕಡಿಮೆ ಖರ್ಚು ಮಾಡಿ – ನಮ್ಮ ವಿಶೇಷ ಪ್ರವಾಸ ಪ್ಯಾಕೇಜ್‌ಗಳೊಂದಿಗೆ ಸಾಹಸ ನಿಮ್ಮನ್ನು ಕಾಯುತ್ತಿದೆ!",
    contactDescription: "ನಿಮ್ಮ ಬಸ್ ಬುಕಿಂಗ್ ಸಂಬಂಧಿಸಿದ ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳು ಅಥವಾ ಕಾಳಜಿಗಳಿಗೆ ನಾವು ಇಲ್ಲಿ ಸಹಾಯ ಮಾಡಲು ಸಿದ್ಧರಿದ್ದೇವೆ.",
    phoneSupport: "ಫೋನ್ ಬೆಂಬಲ",
    supportHoursWeek: "ಸೋಮವಾರದಿಂದ ಶನಿವಾರ, ಬೆಳಿಗ್ಗೆ 9 ರಿಂದ ಸಂಜೆ 6",
    email: "ಇಮೇಲ್",
    responseTime: "ನಾವು ಸಾಧ್ಯವಾದಷ್ಟು ಬೇಗ ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತೇವೆ",
    officeAddress1: "ಸೂರ್ಯೋದಯ ಶಾಲೆಯ ಬಳಿ, ಹೆಸರಘಟ್ಟ ಹೊಬಳಿ",
    officeAddress2: "ಯಲಹಂಕ ತಾಲ್ಲೂಕು ಬೆಂಗಳೂರು ಉತ್ತರ",
    officeAddress3: "ಕರ್ನಾಟಕ - 560064",
    supportHours: "ಬೆಂಬಲ ಸಮಯಗಳು",
    weekdayHours: "ಸೋಮವಾರದಿಂದ ಶುಕ್ರವಾರ: ಬೆಳಿಗ್ಗೆ 9 ರಿಂದ ರಾತ್ರಿ 8",
    saturdayHours: "ಶನಿವಾರ: ಬೆಳಿಗ್ಗೆ 10 ರಿಂದ ಸಂಜೆ 6",
    sundayHours: "ಭಾನುವಾರ: ಮುಚ್ಚಿದೆ",
    followUs: "ನಮ್ಮನ್ನು ಅನುಸರಿಸಿ",
    contactForm: "ಸಂಪರ್ಕ ಫಾರ್ಮ್",
    supportOptions: "ಬೆಂಬಲ ಆಯ್ಕೆಗಳು",
    sendMessage: "ನಮಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ",
    name: "ಹೆಸರು",
    yourName: "ನಿಮ್ಮ ಹೆಸರು",
    yourEmail: "ನಿಮ್ಮ@ಇಮೇಲ್.ಕಾಂ",
    subject: "ವಿಷಯ",
    soda:" ನಿಮ್ಮಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಿದ ಅದ್ಭುತ ಪ್ರಯಾಣಗಳು!",
    howCanWeHelp: "ನಾವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?",
    message: "ಸಂದೇಶ",
    yourMessage: "ನಿಮ್ಮ ಸಂದೇಶ",
    cancelandRefund:"ರದ್ದುಪಡಿಸುವಿಕೆ ಮತ್ತು ಹಣ ಹಿಂತಿರುಗಿಸುವ ನೀತಿ",
    sending: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
    messageSentSuccess: "ಸಂದೇಶವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ",
    messageFailed: "ಸಂದೇಶ ಕಳುಹಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    supportTicket: "ಬೆಂಬಲ ಟಿಕೆಟ್ ತೆರೆಯಿರಿ",
    supportTicketDesc: "ವಿವರವಾದ ಸಹಾಯಕ್ಕಾಗಿ ಬೆಂಬಲ ಟಿಕೆಟ್ ಸಲ್ಲಿಸಿ",
    scheduleCall: "ಕರೆ ಶೆಡ್ಯೂಲ್ ಮಾಡಿ",
    scheduleCallDesc: "ನಮ್ಮ ಬೆಂಬಲ ತಂಡದೊಂದಿಗೆ ಕರೆ ಬುಕ್ ಮಾಡಿ",
    bookingModifications: "ಬುಕಿಂಗ್ ಮಾರ್ಪಾಡುಗಳು",
    bookingModificationsDesc: "ನಿಮ್ಮ ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಬುಕಿಂಗ್ ಅನ್ನು ಬದಲಾಯಿಸಿ ಅಥವಾ ರದ್ದುಗೊಳಿಸಿ",
    emailSupport: "ಇಮೇಲ್ ಬೆಂಬಲ",
    emailSupportDesc: "ತುರ್ತಲ್ಲದ ಸಮಸ್ಯೆಗಳಿಗಾಗಿ ನಮಗೆ ಇಮೇಲ್ ಕಳುಹಿಸಿ",
    responseTimes: "ನಿರೀಕ್ಷಿತ ಪ್ರತಿಕ್ರಿಯೆ ಸಮಯಗಳು",
    phoneResponse: "ಫೋನ್ ಬೆಂಬಲ: ತಕ್ಷಣದಿಂದ 15 ನಿಮಿಷಗಳವರೆಗೆ",
    ticketResponse: "ಬೆಂಬಲ ಟಿಕೆಟ್ಗಳು: 4 ಗಂಟೆಗಳೊಳಗೆ",
    emailResponse: "ಇಮೇಲ್ ವಿಚಾರಣೆಗಳು: 24 ಗಂಟೆಗಳೊಳಗೆ",
    termsSubtitle: "ಪ್ರಶ್ನೆಗಳಿಂದ ಸಾಹಸಗಳವರೆಗೆ, ನಾವು ನಿಮ್ಮೊಂದಿಗೆ ಇದ್ದೇವೆ",
    termsAcceptanceTitle: "ನಿಯಮಗಳ ಸ್ವೀಕಾರ",
    termsAcceptanceContent: "NanduBus ಬುಕಿಂಗ್ ವೆಬ್ಸೈಟ್ ಅನ್ನು ಪ್ರವೇಶಿಸುವ ಮತ್ತು ಬಳಸುವ ಮೂಲಕ, ನೀವು ಈ ಕೆಳಗಿನ ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳನ್ನು ಪಾಲಿಸಲು ಮತ್ತು ಬದ್ಧರಾಗಲು ಒಪ್ಪುತ್ತೀರಿ. ನೀವು ಈ ನಿಯಮಗಳೊಂದಿಗೆ ಒಪ್ಪಿಗೆಯನ್ನು ನೀಡದಿದ್ದರೆ, ದಯವಿಟ್ಟು ಈ ವೆಬ್ಸೈಟ್ ಅನ್ನು ಬಳಸಬೇಡಿ.",
    termsBookingTitle: "ಬುಕಿಂಗ್ ಪ್ರಕ್ರಿಯೆ",
    termsBookingPoint1: "ಬುಕಿಂಗ್ ಪ್ರಕ್ರಿಯೆಯ ಸಮಯದಲ್ಲಿ ಬಳಕೆದಾರರು ನಿಖರವಾದ ಮತ್ತು ಸಂಪೂರ್ಣ ಮಾಹಿತಿಯನ್ನು ಒದಗಿಸಬೇಕು.",
    termsBookingPoint2: "ದೃಢೀಕರಣಕ್ಕೆ ಮುಂಚೆ ಬುಕಿಂಗ್ ವಿವರಗಳ ನಿಖರತೆಯನ್ನು ಪರಿಶೀಲಿಸುವುದು ಬಳಕೆದಾರರ ಹೊಣೆ.",
    termsBookingPoint3: "ಯಾವುದೇ ಬುಕಿಂಗ್ ಅನ್ನು ರದ್ದುಗೊಳಿಸುವ ಅಥವಾ ನಿರಾಕರಿಸುವ ಹಕ್ಕನ್ನು NandhuBus ತನ್ನ ವಿವೇಚನೆಗೆ ಅನುಗುಣವಾಗಿ ಕಾಯ್ದಿರಿಸಿದೆ.",
    termsPaymentsTitle: "ಪಾವತಿಗಳು",
    termsPaymentsPoint1: "ಬಸ್ ಬುಕಿಂಗ್ಗಳಿಗೆ ಪಾವತಿಯನ್ನು ವೆಬ್ಸೈಟ್ನಲ್ಲಿ ಅನುಮೋದಿತ ಪಾವತಿ ವಿಧಾನಗಳ ಮೂಲಕ ಮಾಡಬೇಕು.",
    termsPaymentsPoint2: "ಮುನ್ಸೂಚನೆಯಿಲ್ಲದೆ ಬೆಲೆಗಳು ಬದಲಾಗಬಹುದು, ಮತ್ತು ಯಾವುದೇ ವ್ಯತ್ಯಾಸಗಳಿಗೆ NandhuBus ಜವಾಬ್ದಾರನಾಗಿರುವುದಿಲ್ಲ.",
    termsCancellationsTitle: "ರದ್ದತಿ ಮತ್ತು ಮರುಪಾವತಿ",
    termsCancellationsPoint1: "ರದ್ದತಿ ನೀತಿಗಳು ಮಾರ್ಗ ಮತ್ತು ಆಪರೇಟರ್ ಅನುಸಾರ ಬದಲಾಗುತ್ತದೆ. ಬಳಕೆದಾರರು ತಮ್ಮ ಬುಕಿಂಗ್ ಸಂಬಂಧಿತ ನಿರ್ದಿಷ್ಟ ರದ್ದತಿ ನೀತಿಯನ್ನು ಪರಿಶೀಲಿಸಲು ಸಲಹೆ ನೀಡಲಾಗುತ್ತದೆ.",
    termsCancellationsPoint2: "ಮರುಪಾವತಿ ವಿನಂತಿಗಳನ್ನು ಅನ್ವಯಿಸುವ ರದ್ದತಿ ನೀತಿಗೆ ಅನುಗುಣವಾಗಿ ಮಾಡಬೇಕು.",
    termsAccountsTitle: "ಬಳಕೆದಾರ ಖಾತೆಗಳು",
    termsAccountsPoint1: "ಬಳಕೆದಾರರು ತಮ್ಮ ಖಾತೆ ಮಾಹಿತಿ ಮತ್ತು ಪಾಸ್ವರ್ಡ್ಗಳ ಗೋಪ್ಯತೆಯನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳುವ ಜವಾಬ್ದಾರಿಯನ್ನು ಹೊಂದಿದ್ದಾರೆ.",
    termsAccountsPoint2: "ಬಳಕೆದಾರರು ತಮ್ಮ ಖಾತೆಯ ಅಡಿಯಲ್ಲಿ ಸಂಭವಿಸುವ ಎಲ್ಲಾ ಚಟುವಟಿಕೆಗಳಿಗೆ ಜವಾಬ್ದಾರರಾಗಿರುತ್ತಾರೆ.",
    termsPrivacyTitle: "ಗೌಪ್ಯತಾ ನೀತಿ",
    termsPrivacyContent: "NandhuBus ವೆಬ್ಸೈಟ್ನಲ್ಲಿರುವ ಎಲ್ಲಾ ವಿಷಯ, ಪಠ್ಯ, ಗ್ರಾಫಿಕ್ಸ್, ಲೋಗೋಗಳು ಮತ್ತು ಚಿತ್ರಗಳು NandhuBus ನ ಸ್ವತ್ತು ಮತ್ತು ಬೌದ್ಧಿಕ ಸ್ವತ್ತು ಕಾನೂನುಗಳಿಂದ ರಕ್ಷಿಸಲ್ಪಟ್ಟಿವೆ.",
    termsLiabilityTitle: "ಜವಾಬ್ದಾರಿಯ ಮಿತಿ",
    termsLiabilityContent: "ವೆಬ್ಸೈಟ್ ಅಥವಾ ಸೇವೆಗಳನ್ನು ಬಳಸಲು ಅಸಮರ್ಥತೆ ಅಥವಾ ಬಳಕೆಯಿಂದ ಉಂಟಾಗುವ ಯಾವುದೇ ನೇರ, ಪರೋಕ್ಷ, ಆಕಸ್ಮಿಕ, ವಿಶೇಷ ಅಥವಾ ಪರಿಣಾಮಕಾರಿ ನಷ್ಟಗಳಿಗೆ NanduBus ಜವಾಬ್ದಾರನಾಗಿರುವುದಿಲ್ಲ.",
    termsLawTitle: "ಆಡಳಿತಾತ್ಮಕ ಕಾನೂನು",
    termsLawContent: "ಈ ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳನ್ನು ಭಾರತೀಯ ನ್ಯಾಯವ್ಯಾಪ್ತಿಯ ಕಾನೂನುಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ನಿಯಂತ್ರಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಅರ್ಥೈಸಲಾಗುತ್ತದೆ.",
    termsFinalNote: "NandhuBus ಬಸ್ ಬುಕಿಂಗ್ ವೆಬ್ಸೈಟ್ ಅನ್ನು ಬಳಸುವ ಮೂಲಕ, ನೀವು ಈ ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳನ್ನು ಓದಿದ್ದೀರಿ, ಅರ್ಥಮಾಡಿಕೊಂಡಿದ್ದೀರಿ ಮತ್ತು ಅವುಗಳಿಗೆ ಬದ್ಧರಾಗಲು ಒಪ್ಪುತ್ತೀರಿ ಎಂದು ನೀವು ಒಪ್ಪಿಕೊಳ್ಳುತ್ತೀರಿ. NanduBus ಹಿಂದಿನ ಸೂಚನೆಯಿಲ್ಲದೆ ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ಈ ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳನ್ನು ಮಾರ್ಪಡಿಸುವ ಅಥವಾ ನವೀಕರಿಸುವ ಹಕ್ಕನ್ನು ಕಾಯ್ದಿರಿಸಿದೆ. ಬಳಕೆದಾರರು ಈ ನಿಯಮಗಳನ್ನು ನಿಯಮಿತವಾಗಿ ಪರಿಶೀಲಿಸುವ ಜವಾಬ್ದಾರಿಯನ್ನು ಹೊಂದಿದ್ದಾರೆ.",
    loginDiscountMessage: "ರೋಚಕವಾದ ರಿಯಾಯಿತಿಗಳು ಮತ್ತು ಕ್ಯಾಶ್‌ಬ್ಯಾಕ್‌ಗಳನ್ನು ಪಡೆಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ!!",
    invalidOtp: "ಅಮಾನ್ಯ OTP",
    requiredField: "ಅಗತ್ಯವಿದೆ",
    invalidOtpTryAgain: "ಅಮಾನ್ಯ OTP, ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    otpSentTo: "OTP ಕಳುಹಿಸಲಾಗಿದೆ",
    enterOtp: "OTP ನಮೂದಿಸಿ",
    verifying: "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    verifyOtp: "OTP ಪರಿಶೀಲಿಸಿ",
    otpResentSuccess: "OTP ಅನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಮರುಕಳುಹಿಸಲಾಗಿದೆ!",
    changeNumber: "ಸಂಖ್ಯೆಯನ್ನು ಬದಲಾಯಿಸಿ",
    resendOtp: "OTP ಅನ್ನು ಮರುಕಳುಹಿಸಿ",
    invalidPhoneNumber: "ಅಮಾನ್ಯ ಫೋನ್ ಸಂಖ್ಯೆ",
    mobileNumber: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    enterMobileNumber: "ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    generateOtp: "OTP ಉತ್ಪಾದಿಸಿ",
    termsAgreement1: "ಸೈನ್ ಅಪ್ ಮಾಡುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ",
    termsAgreement2: "ಮತ್ತು",
    privacyPolicy:"ಗೌಪ್ಯತಾ ನೀತಿ.",
    tc:"ನಿಯಮಗಳು",
    cu:"ಸಂಪರ್ಕಿಸಿ",
    mt:"ಪ್ರವಾಸಗಳು",
    welcome: "ಸ್ವಾಗತ!",
hi: "ನಮಸ್ಕಾರ",
introduction: "ಪರಿಚಯ",
introductionContent: "ಈ ಗೌಪ್ಯತಾ ನೀತಿ, ನೀವು ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಬಳಸುವಾಗ ನಂದುಬಸ್ ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಹೇಗೆ ಸಂಗ್ರಹಿಸುತ್ತದೆ, ಬಳಸುತ್ತದೆ ಮತ್ತು ರಕ್ಷಿಸುತ್ತದೆ ಎಂಬುದನ್ನು ವಿವರಿಸುತ್ತದೆ. ನೀವು ನಮ್ಮ ಸೇವೆಗೆ ಪ್ರವೇಶಿಸುವ ಅಥವಾ ಬಳಸುವ ಮೂಲಕ, ನೀವು ಕೆಳಗಿನ ಶರತ್ತುಗಳನ್ನು ಒಪ್ಪಿಸುತ್ತೀರಿ. ನಾವು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ರಕ್ಷಿಸಲು ಮತ್ತು ಅನ್ವಯಿಸುವ ಗೌಪ್ಯತಾ ಕಾನೂನುಗಳಿಗೆ ಅನುಗುಣವಾಗಿ ಪಾರದರ್ಶಕತೆಯನ್ನು ಖಾತರಿಪಡಿಸಲು ಬದ್ಧರಾಗಿದ್ದೇವೆ. ಪ್ರಶ್ನೆಗಳಿಗಾಗಿ, ದಯವಿಟ್ಟು +917090007776/support@nandhubus.com ಗೆ ಸಂಪರ್ಕಿಸಿ.",
interpretation: "ವ್ಯಾಖ್ಯಾನ ಮತ್ತು ವ್ಯಾಖ್ಯಾನಗಳು",
interpretationContent: "ಪ್ರಾಥಮಿಕ ಅಕ್ಷರದಲ್ಲಿ ಇರುವ ಶಬ್ದಗಳು ಕೆಳಗಿನ ಶರತ್ತುಗಳ ಅಡಿಯಲ್ಲಿ ವ್ಯಾಖ್ಯಾಸಿತವಾದ ಅರ್ಥಗಳನ್ನು ಹೊಂದಿವೆ. ಈ ವ್ಯಾಖ್ಯಾಸಗಳು ಶಬ್ದಗಳು ಏಕವಚನ ಅಥವಾ ಬಹುವಚನದಲ್ಲಿ ಕಾಣಿಸಿದಾಗಲೂ ಅನ್ವಯಿಸುತ್ತವೆ.",
definitions: "ವ್ಯಾಖ್ಯಾನಗಳು",
registeredAccount: "ನೋಂದಾಯಿತ ಖಾತೆ: ನಿಮ್ಮನ್ನು ನಮ್ಮ ವೇದಿಕೆಯ ವೈಶಿಷ್ಟ್ಯಗಳು ಮತ್ತು ಸೇವೆಗಳಿಗೆ ಪ್ರವೇಶಿಸಲು ಅನುಮತಿಸುವ ವೈಯಕ್ತಿಕ ಲಾಗಿನ್ ಪ್ರಮಾಣಪತ್ರ.",
corporateAffiliates: "ಕಾರ್ಪೊರೇಟ್ ಸಹಚರಗಳು: ನಾವೆಲ್ಲರೊಂದಿಗೆ ನೇರವಾಗಿ ಅಥವಾ ಪರೋಕ್ಷವಾಗಿ ನಿಯಂತ್ರಣ ಹೊಂದಿರುವ, ನಿಯಂತ್ರಿತ ಅಥವಾ ಸಾಮಾನ್ಯ ಮಾಲೀಕತ್ವವನ್ನು ಹಂಚಿಕೊಳ್ಳುವ ಸಂಸ್ಥೆಗಳು, ಅಲ್ಲಿ 'ನಿಯಂತ್ರಣ' ಎಂದರೆ 50% ಕ್ಕಿಂತ ಹೆಚ್ಚು ಮತದಾನ ಶೇರುಗಳು ಅಥವಾ ನಿರ್ಧಾರ ಕೈಗಾರಿಕೆಯನ್ನು ಹೊಂದುವುದು.",
businessEntity: "ವ್ಯವಹಾರ ಸಂಸ್ಥೆ: 1ನೇ ಮಹಡಿ, ಆರ್ ಡಿ ರಾಜಣ್ಣ ಸಂಕೀರ್ಣ, ರಾಜನಕುಂಟೆ, ಯelahಂಕಾ ತಾಲ್ಲೂಕು, ಬೆಂಗಳೂರು, ಕರ್ನಾಟಕ, ಭಾರತ (560064) ನಲ್ಲಿ ನೋಂದಾಯಿತ ಸೀಬೆಡ್2ಕ್ರೆಸ್ಟ್ ಟೆಕ್ನೋಲಾಜೀಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್ ಅನ್ನು ಉಲ್ಲೇಖಿಸುತ್ತದೆ.",
browserCookies: "ಬ್ರೌಸರ್ ಕುಕೀಗಳು: ನೀವು ನಮ್ಮ ವೆಬ್‌ಸೈಟ್‌ಗೆ ಭೇಟಿ ನೀಡುವಾಗ ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿ ಸಂಗ್ರಹಿತವಾಗುವ ಸಣ್ಣ ಪಠ್ಯ ಫೈಲ್‌ಗಳು, ಕಾರ್ಯಕ್ಷಮತೆಯನ್ನು ಸುಧಾರಿಸಲು ಮತ್ತು ಬಳಕೆದಾರ ವರ್ತನೆಯನ್ನು ವಿಶ್ಲೇಷಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ.",
governingRegion: "ನಿಯಂತ್ರಣ ಪ್ರದೇಶ: ಈ ಗೌಪ್ಯತಾ ನೀತಿಗೆ ಅನ್ವಯಿಸುವ ಕರ್ನಾಟಕ ರಾಜ್ಯ, ಭಾರತ.",
electronicDevice: "ಇಲೆಕ್ಟ್ರಾನಿಕ್ ಸಾಧನ: ನಮ್ಮ ಸೇವೆಗಳಿಗೆ ಸಂಪರ್ಕಿಸಲು ಮತ್ತು ಪರಸ್ಪರ ಕ್ರಿಯೆಗೊಳ್ಳಲು ಸಾಮರ್ಥ್ಯವಿರುವ ಯಾವುದೇ ಹಾರ್ಡ್‌ವೇರ್ ಸಾಧನ (ಉದಾಹರಣೆಗೆ, ಕಂಪ್ಯೂಟರ್‌ಗಳು, ಸ್ಮಾರ್ಟ್‌ಫೋನ್‌ಗಳು, ಟ್ಯಾಬ್ಲೆಟ್‌ಗಳು).",
personalInformation: "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ: ನಿರ್ದಿಷ್ಟ ವ್ಯಕ್ತಿಯನ್ನು ಗುರುತಿಸಲು ಬಳಸಬಹುದಾದ ಯಾವುದೇ ಡೇಟಾ—ಅದರಲ್ಲಿಯೇ ಅಥವಾ ಇತರ ಮಾಹಿತಿಯೊಂದಿಗೆ ಸಂಯೋಜಿತವಾಗಿರಬಹುದು.",
digitalServices: "ಡಿಜಿಟಲ್ ಸೇವೆಗಳು: ನಂದುಬಸ್ ಆನ್‌ಲೈನ್ ವೇದಿಕೆಯು, nandhubus.in ಮೂಲಕ ಪ್ರವೇಶಿಸಲು ಲಭ್ಯವಿದೆ.",
authorizedVendors: "ಅಧಿಕೃತ ಪೂರೈಕೆದಾರರು: ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಒದಗಿಸಲು, ನಿರ್ವಹಿಸಲು ಅಥವಾ ವಿಶ್ಲೇಷಿಸಲು ಸಹಾಯ ಮಾಡುವ ವಿಶ್ವಾಸಾರ್ಹ ತೃತೀಯ ಪಕ್ಷದ ಸೇವಾ ಪೂರೈಕೆದಾರರು, ಕಠಿಣ ಗೌಪ್ಯತಾ ಒಪ್ಪಂದಗಳ ಅಡಿಯಲ್ಲಿ.",
automatedUsageData: "ಸ್ವಯಂಚಾಲಿತ ಬಳಕೆ ಡೇಟಾ: ನಮ್ಮ ಸೇವೆಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಪರಸ್ಪರ ಕ್ರಿಯೆಗಳನ್ನು ಮೂಲಕ ಪಾಸಿವ್ ಆಗಿ ಸಂಗ್ರಹಿತ ಮಾಹಿತಿಯು (ಉದಾಹರಣೆಗೆ, ಸೆಷನ್ ಅವಧಿ, ಭೇಟಿ ನೀಡಿದ ಪುಟಗಳು).",
endUser : "ಅಂತಿಮ ಬಳಕೆದಾರ: ತಮ್ಮದೇ ಆದ ಅಥವಾ ಇತರರ ಪರವಾಗಿ ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸುವ ಅಥವಾ ಬಳಸುವ ಯಾವುದೇ ವ್ಯಕ್ತಿ ಅಥವಾ ಕಾನೂನು ಸಂಸ್ಥೆ (ಉದಾಹರಣೆಗೆ, ಕಂಪನಿಯು).",
collectingData: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾ ಸಂಗ್ರಹಣೆ ಮತ್ತು ಬಳಕೆ",
typesOfDataCollected: "ಸಂಗ್ರಹಿಸಲಾದ ಡೇಟಾ ಪ್ರಕಾರಗಳು",
personalData: "ವೈಯಕ್ತಿಕ ಡೇಟಾ: ನಮ್ಮ ಸೇವೆಯನ್ನು ಬಳಸುವಾಗ, ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಲು ಅಥವಾ ಗುರುತಿಸಲು ಬಳಸಬಹುದಾದ ಕೆಲವು ವೈಯಕ್ತಿಕವಾಗಿ ಗುರುತಿಸಬಹುದಾದ ಮಾಹಿತಿಯನ್ನು ನಮಗೆ ಒದಗಿಸಲು ನೀವು ಕೇಳಬಹುದು. ಇದರಲ್ಲಿ ಒಳಗೊಂಡಿರಬಹುದು: ಇಮೇಲ್ ವಿಳಾಸ, ಮೊದಲ ಹೆಸರು ಮತ್ತು ಕೊನೆಯ ಹೆಸರು, ದೂರವಾಣಿ ಸಂಖ್ಯೆ, ವಿಳಾಸ, ರಾಜ್ಯ, ಪ್ರಾಂತ್ಯ, ZIP/ಪೋಸ್ಟಲ್ ಕೋಡ್, ನಗರ.",
usageData: "ಬಳಕೆ ಡೇಟಾ: ಸೇವೆಯನ್ನು ಬಳಸುವಾಗ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸಂಗ್ರಹಿಸಲಾಗುತ್ತದೆ. ಇದರಲ್ಲಿ ನಿಮ್ಮ ಸಾಧನದ IP ವಿಳಾಸ, ಬ್ರೌಸರ್ ಪ್ರಕಾರ, ಬ್ರೌಸರ್ ಆವೃತ್ತಿ, ಭೇಟಿ ನೀಡಿದ ಪುಟಗಳು, ಭೇಟಿ ಸಮಯ, ಪುಟಗಳಲ್ಲಿ ಕಳೆದ ಸಮಯ, ಸಾಧನ ಗುರುತಿಸುವಿಕೆ ಮತ್ತು ಇತರ ನಿರ್ಣಾಯಕ ಡೇಟಾ ಒಳಗೊಂಡಿರಬಹುದು. ನೀವು ಮೊಬೈಲ್ ಸಾಧನದ ಮೂಲಕ ಸೇವೆಗೆ ಪ್ರವೇಶಿಸಿದಾಗ, ನಾವು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಕೆಲವು ಹೆಚ್ಚುವರಿ ಮಾಹಿತಿಯನ್ನು ಸಂಗ್ರಹಿಸಬಹುದು, ಇದರಲ್ಲಿ, ಆದರೆ ಇದಕ್ಕೆ ಮಾತ್ರ ಸೀಮಿತವಲ್ಲ: ಮೊಬೈಲ್ ಸಾಧನದ ಪ್ರಕಾರ ಮತ್ತು ವಿಶಿಷ್ಟ ID, ಮೊಬೈ",
mobileDevice: "ಮೊಬೈಲ್ ಸಾಧನದ IP ವಿಳಾಸ, ಮೊಬೈಲ್ ಕಾರ್ಯಾಚರಣಾ ವ್ಯವಸ್ಥೆ, ಮೊಬೈಲ್ ಬ್ರೌಸರ್ ಪ್ರಕಾರ, ಮೊಬೈಲ್ ಸಾಧನ ಗುರುತಿಸುವಿಕೆ, ಇತರ ನಿರ್ಣಾಯಕ ಡೇಟಾ.",
trackingTechnologies: "ಟ್ರ್ಯಾಕಿಂಗ್ ತಂತ್ರಜ್ಞಾನಗಳು ಮತ್ತು ಕುಕೀಗಳು",
trackingTechnologiesContent: "ನಾವು ನಮ್ಮ ಸೇವೆಯಲ್ಲಿ ಚಲನೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಮತ್ತು ಕೆಲವು ಮಾಹಿತಿಯನ್ನು ಸಂಗ್ರಹಿಸಲು ಕುಕೀಗಳು ಮತ್ತು ಸಮಾನವಾದ ಟ್ರ್ಯಾಕಿಂಗ್ ತಂತ್ರಜ್ಞಾನಗಳನ್ನು ಬಳಸುತ್ತೇವೆ. ಬಳಸುವ ಟ್ರ್ಯಾಕಿಂಗ್ ತಂತ್ರಜ್ಞಾನಗಳು ಬಿಕಾನ್‌ಗಳು, ಟ್ಯಾಗ್‌ಗಳು ಮತ್ತು ಮಾಹಿತಿಯನ್ನು ಸಂಗ್ರಹಿಸಲು ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಮತ್ತು ನಮ್ಮ ಸೇವೆಯನ್ನು ಸುಧಾರಿಸಲು ಮತ್ತು ವಿಶ್ಲೇಷಿಸಲು ಬಳಸುವ ಸ್ಕ್ರಿಪ್ಟ್‌ಗಳನ್ನು ಒಳಗೊಂಡಿವೆ.",
cookies: "ಕುಕೀಗಳು ಅಥವಾ ಬ್ರೌಸರ್ ಕುಕೀಗಳು: ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿ ಇರಿಸಲಾಗುವ ಸಣ್ಣ ಫೈಲ್. ನೀವು ನಿಮ್ಮ ಬ್ರೌಸರ್ ಅನ್ನು ಎಲ್ಲಾ ಕುಕೀಗಳನ್ನು ನಿರಾಕರಿಸಲು ಅಥವಾ ಕುಕೀ ಕಳುಹಿಸಲಾಗುವಾಗ ಸೂಚಿಸಲು ಸೂಚಿಸಬಹುದು. ಆದರೆ, ನೀವು ಕುಕೀಗಳನ್ನು ಒಪ್ಪದಿದ್ದರೆ, ನೀವು ನಮ್ಮ ಸೇವೆಯ ಕೆಲವು ಭಾಗಗಳನ್ನು ಬಳಸಲು ಸಾಧ್ಯವಾಗದಿರಬಹುದು.",
webBeacons: "ವೆಬ್ ಬಿಕಾನ್ಸ್: ಪುಟಗಳನ್ನು ಭೇಟಿಯಾಗಿ, ಇಮೇಲ್ ತೆರೆಯುವ ಮತ್ತು ಇತರ ಸಂಬಂಧಿತ ವೆಬ್‌ಸೈಟ್ ಅಂಕಿಅಂಶಗಳಿಗಾಗಿ ಬಳಕೆದಾರರನ್ನು ಎಣಿಸಲು ಕಂಪನಿಯು ಅನುಮತಿಸುವ ಸಣ್ಣ ಇಲೆಕ್ಟ್ರಾನಿಕ್ ಫೈಲ್‌ಗಳು (ಸ್ಪಷ್ಟ ಗಿಫ್‌ಗಳು, ಪಿಕ್ಸೆಲ್ ಟ್ಯಾಗ್‌ಗಳು, ಏಕ-ಪಿಕ್ಸೆಲ್ ಗಿಫ್‌ಗಳು).",
necessaryCookies: "ಅಗತ್ಯ / ಪ್ರಮುಖ ಕುಕೀಗಳು: ಪ್ರಕಾರ: ಸೆಷನ್ ಕುಕೀಗಳು. ನಿರ್ವಹಣೆ: ನಮ್ಮಿಂದ. ಉದ್ದೇಶ: ಈ ಕುಕೀಗಳು ವೆಬ್‌ಸೈಟ್ ಮೂಲಕ ಲಭ್ಯವಿರುವ ಸೇವೆಗಳನ್ನು ಒದಗಿಸಲು ಮತ್ತು ಅದರ ಕೆಲವು ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಬಳಸಲು ನಿಮಗೆ ಅನುಮತಿಸಲು ಅಗತ್ಯವಿದೆ. ಇವು ಬಳಕೆದಾರರನ್ನು ದೃಢೀಕರಿಸಲು ಮತ್ತು ಬಳಕೆದಾರ ಖಾತೆಗಳ ದುರುಪಯೋಗವನ್ನು ತಡೆಯಲು ಸಹಾಯ ಮಾಡುತ್ತವೆ.",
cookiesPolicy: "ಕುಕೀ ನೀತಿ / ಕುಕೀ ನೋಟಿಸ್ ಸ್ವೀಕಾರ ಕುಕೀಗಳು: ಪ್ರಕಾರ: ಶಾಶ್ವತ ಕುಕೀಗಳು. ನಿರ್ವಹಣೆ: ನಮ್ಮಿಂದ. ಉದ್ದೇಶ: ಈ ಕುಕೀಗಳು ಬಳಕೆದಾರರು ವೆಬ್‌ಸೈಟ್ನಲ್ಲಿ ಕುಕೀಗಳನ್ನು ಬಳಸಲು ಒಪ್ಪಿಕೊಂಡಿದ್ದಾರೆಯೇ ಎಂಬುದನ್ನು ಗುರುತಿಸುತ್ತವೆ.",
functionalityCookies: "ಫಂಕ್ಷನಾಲಿಟಿ ಕುಕೀಗಳು: ಪ್ರಕಾರ: ಶಾಶ್ವತ ಕುಕೀಗಳು. ನಿರ್ವಹಣೆ: ನಮ್ಮಿಂದ. ಉದ್ದೇಶ: ಈ ಕುಕೀಗಳು ನೀವು ವೆಬ್‌ಸೈಟ್ನಲ್ಲಿ ಬಳಸುವಾಗ ನೀವು ಮಾಡಿದ ಆಯ್ಕೆಗಳನ್ನು ನೆನೆಸಲು ನಮಗೆ ಅನುಮತಿಸುತ್ತವೆ, ಉದಾಹರಣೆಗೆ ನಿಮ್ಮ ಲಾಗಿನ್ ವಿವರಗಳು ಅಥವಾ ಭಾಷಾ ಆಯ್ಕೆ.",
useOfPersonalData: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾ ಬಳಕೆ",
useOfPersonalDataContent: "ಕಂಪನಿಯು ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಕೆಳಗಿನ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಬಳಸಬಹುದು:",
serviceProvision: "ಸೇವಾ ಒದಗಿಸುವಿಕೆ ಮತ್ತು ನಿರ್ವಹಣೆ: ನಿರಂತರ ವೇದಿಕೆ ಕಾರ್ಯಾಚರಣೆಯನ್ನು ಖಾತರಿಪಡಿಸುವುದು, ವ್ಯವಸ್ಥೆಯ ಕಾರ್ಯಕ್ಷಮತೆ ಮತ್ತು ಬಳಕೆದಾರ ಮಾದರಿಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡುವುದು.",
accountAdministration: "ಖಾತೆ ನಿರ್ವಹಣೆ: ಬಳಕೆದಾರ ನೋಂದಣಿ ಮತ್ತು ದೃಢೀಕರಣವನ್ನು ಸುಲಭಗೊಳಿಸುವುದು, ವೇದಿಕೆಯ ವೈಶಿಷ್ಟ್ಯಗಳು ಮತ್ತು ಕಾರ್ಯಕ್ಷಮತೆಗಳಿಗೆ ಪ್ರವೇಶವನ್ನು ಸಕ್ರಿಯಗೊಳಿಸುವುದು.",
contractualObligations: "ಒಪ್ಪಂದ ಬದ್ಧತೆಗಳು: ಖರೀದಿ ಒಪ್ಪಂದಗಳನ್ನು ಕಾರ್ಯಗತಗೊಳಿಸುವುದು, ಸೇವಾ ಬದ್ಧತೆಗಳನ್ನು ಪೂರೈಸುವುದು.",
userCommunications: "ಬಳಕೆದಾರ ಸಂವಹನಗಳು: ಹಲವಾರು ಚಾನೆಲ್‌ಗಳ ಮೂಲಕ ಸೇವೆ-ಸಂಬಂಧಿತ ಅಧಿಸೂಚನೆಗಳನ್ನು ಒದಗಿಸುವುದು (ಇಮೇಲ್, SMS, ಪುಷ್ ಅಧಿಸೂಚನೆಗಳು), ಪ್ರಮುಖ ವೇದಿಕೆ ನವೀಕರಣಗಳು ಮತ್ತು ಘೋಷಣೆಗಳನ್ನು ಒದಗಿಸುವುದು.",
marketingCommunications: "ಮಾರ್ಕೆಟಿಂಗ್ ಸಂವಹನಗಳು: ಸಂಬಂಧಿತ ಆಫರ್‌ಗಳ ಬಗ್ಗೆ ಪ್ರಸ್ತುತ ಪ್ರಚಾರಾತ್ಮಕ ವಿಷಯವನ್ನು ಹಂಚುವುದು, ವೈಯಕ್ತಿಕ ಸೇವಾ ಶಿಫಾರಸುಗಳನ್ನು ಒದಗಿಸುವುದು.",
customerSupport: "ಗ್ರಾಹಕ ಬೆಂಬಲ: ಬಳಕೆದಾರರ ಪ್ರಶ್ನೆಗಳನ್ನು ಮತ್ತು ಸೇವಾ ವಿನಂತಿಗಳನ್ನು ಪರಿಹರಿಸುವುದು, ತಾಂತ್ರಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ಮತ್ತು ಖಾತೆ ವಿಷಯಗಳನ್ನು ಪರಿಹರಿಸುವುದು.",
corporateTransactions: "ಕೋರ್ಪೊರೇಟ್ ವ್ಯವಹಾರಗಳು: ಸಾಧ್ಯವಾದ mergers, acquisitions ಅಥವಾ ಆಸ್ತಿ ವರ್ಗಾವಣೆಗಳನ್ನು ಸುಲಭಗೊಳಿಸುವುದು, due diligence ಪ್ರಕ್ರಿಯೆಗಳನ್ನು ಬೆಂಬಲಿಸುವುದು.",
serviceOptimization: "ಸೇವಾ ಸುಧಾರಣೆ: ಬಳಕೆದಾರ ಮಾದರಿಗಳನ್ನು ಗುರುತಿಸಲು ಡೇಟಾ ವಿಶ್ಲೇಷಣೆ ನಡೆಸುವುದು, ವೇದಿಕೆಯ ಸುಧಾರಣೆ ಮತ್ತು ವೈಶಿಷ್ಟ್ಯಗಳ ಸುಧಾರಣೆಗಳನ್ನು ಕಾರ್ಯಗತಗೊಳಿಸುವುದು.",
disclosureCircumstances: "ನಾವು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿಯನ್ನು ಕೆಳಗಿನ ಪರಿಸ್ಥಿತಿಗಳಲ್ಲಿ ಬಹಿರಂಗಪಡಿಸಬಹುದು:",
thirdPartyServiceProviders: "ತೃತೀಯ ಪಕ್ಷದ ಸೇವಾ ಪೂರೈಕೆದಾರರು: ಸೇವಾ ವಿಶ್ಲೇಷಣೆ, ಕಾರ್ಯಕ್ಷಮತೆ ಮೇಲ್ವಿಚಾರಣೆ ಮತ್ತು ಗ್ರಾಹಕ ಸಂವಹನಗಳನ್ನು ಒಳಗೊಂಡಂತೆ ಅಗತ್ಯವಿರುವ ವ್ಯಾಪಾರ ಕಾರ್ಯಗಳನ್ನು ನಿರ್ವಹಿಸಲು ನಾವು ವಿಶ್ವಾಸಾರ್ಹ ಪಾಲುದಾರರನ್ನು ಬಳಸುತ್ತೇವೆ, ಕಠಿಣ ಗೌಪ್ಯತಾ ಒಪ್ಪಂದಗಳ ಅಡಿಯಲ್ಲಿ.",
corporateTransactionsDisclosure: "ಕೋರ್ಪೊರೇಟ್ ವ್ಯವಹಾರಗಳು: mergers, acquisitions, ಹಣಕಾಸು ಅಥವಾ ಕಂಪನಿಯ ಆಸ್ತಿ ಮಾರಾಟದ ಸಂದರ್ಭದಲ್ಲಿ ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ವ್ಯಾಪಾರ ಆಸ್ತಿ ಎಂದು ವರ್ಗಾಯಿಸಲಾಗುತ್ತದೆ, ಸೂಕ್ತ ಗೌಪ್ಯತಾ ರಕ್ಷಣೆಯೊಂದಿಗೆ.",
corporateAffiliatesDisclosure: "ಕೋರ್ಪೊರೇಟ್ ಸಹಚರರು: ಈ ಗೌಪ್ಯತಾ ನೀತಿಯ ಶರತ್ತುಗಳು ಮತ್ತು ಭದ್ರತಾ ಮಾನದಂಡಗಳನ್ನು ಪಾಲಿಸುವ ಎಲ್ಲಾ ಸಾಮಾನ್ಯ ನಿಯಂತ್ರಣದ ಅಡಿಯಲ್ಲಿ ಇರುವ ಸಂಸ್ಥೆಗಳೊಂದಿಗೆ ಡೇಟಾವನ್ನು ಹಂಚಬಹುದು.",
strategicPartners: "ಯೋಜಿತ ಪಾಲುದಾರರು: ನಿಮ್ಮಿಗೆ ಸಂಬಂಧಿತ ಉತ್ಪನ್ನಗಳು, ಸೇವೆಗಳು ಅಥವಾ ಪ್ರಚಾರಾತ್ಮಕ ಆಫರ್‌ಗಳನ್ನು ಒದಗಿಸಲು ಆಯ್ಕೆ ಮಾಡಿದ ವ್ಯಾಪಾರ ಸಹಭಾಗಿಗಳೊಂದಿಗೆ.",
publicInteractions: "ಸಾರ್ವಜನಿಕ ಪರಸ್ಪರ ಕ್ರಿಯೆಗಳು: ನೀವು ಸಾರ್ವಜನಿಕ ವೇದಿಕೆ ಪ್ರದೇಶಗಳಲ್ಲಿ ಸ್ವಯಂ-ಸೇವಿತವಾಗಿ ಹಂಚುವ ಮಾಹಿತಿಯು ಇತರ ಬಳಕೆದಾರರಿಗೆ ಲಭ್ಯವಾಗಬಹುದು ಮತ್ತು ನಮ್ಮ ನಿಯಂತ್ರಣವನ್ನು ಮೀರಿಸುವಂತೆ ಪುನಃ ವಿತರಿಸಲಾಗಬಹುದು.",
consentBasedDisclosures: "ಒಪ್ಪಂದ ಆಧಾರಿತ ಬಹಿರಂಗಪಡಿಸುವಿಕೆ: ಈ ನೀತಿಯಲ್ಲಿ ವಿವರಿಸಲಾದ ಯಾವುದೇ ಉದ್ದೇಶಕ್ಕಾಗಿ ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಹಂಚುವ ಮೊದಲು ಸ್ಪಷ್ಟ ಅನುಮೋದನೆ ಪಡೆಯುತ್ತೇವೆ.",
retentionOfData: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾ ಉಳಿಸುವಿಕೆ",
retentionOfDataContent: "ಕಂಪನಿಯು ಈ ಗೌಪ್ಯತಾ ನೀತಿಯಲ್ಲಿ ವಿವರಿಸಲಾದ ಉದ್ದೇಶಗಳನ್ನು ಪೂರೈಸಲು ಅಗತ್ಯವಿರುವಷ್ಟು ಮಾತ್ರ ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಉಳಿಸುತ್ತದೆ, ಕಾನೂನು ಬದ್ಧತೆಗಳನ್ನು ಪಾಲಿಸಲು, ವಿವಾದಗಳನ್ನು ಪರಿಹರಿಸಲು, ಒಪ್ಪಂದಗಳನ್ನು ಜಾರಿಗೆ ತರುವುದಕ್ಕೆ ಮತ್ತು ವ್ಯಾಪಾರ ದಾಖಲೆಗಳನ್ನು ನಿರ್ವಹಿಸಲು. ಬಳಕೆ ಡೇಟಾ ಸಾಮಾನ್ಯವಾಗಿ ಕಡಿಮೆ ಅವಧಿಯ ಕಾಲಾವಧಿಗೆ ಉಳಿಸಲಾಗುತ್ತದೆ, ಆದರೆ ಸೇವಾ ಭದ್ರತೆ, ಕಾರ್ಯಕ್ಷಮತೆ ಸುಧಾರಣೆ ಅಥವಾ ಕಾನೂನು ಅಗತ್ಯಗಳನ್ನು ಪೂರೈಸಲು ಅಗತ್ಯವಿರುವಾಗ ಉಳಿಸಲಾಗುತ್ತದೆ. ಎಲ್ಲಾ ಡೇಟಾ ಉಳಿಸುವಿಕೆ ಅಭ್ಯಾಸಗಳು ಅನ್ವಯಿಸುವ ಕಾನೂನುಗಳು ಮತ್ತು ನಮ್ಮ ಆಂತರಿಕ ಆಡಳಿತ ಮಾನದಂಡಗಳನ್ನು ಪಾಲಿಸುತ್ತವೆ.",
transferOfData: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾ ವರ್ಗಾವಣೆ",
transferOfDataContent: "ಮಾಹಿತಿಯನ್ನು ಸಲ್ಲಿಸುವ ಮೂಲಕ ನೀವು ಆ ವರ್ಗಾವಣೆಗೆ ಒಪ್ಪಿಸುತ್ತೀರಿ. ಕಂಪನಿಯು ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಮತ್ತು ಈ ಗೌಪ್ಯತಾ ನೀತಿಯ ಅನುಸಾರವಾಗಿ ಚಿಕಿತ್ಸೆ ನೀಡಲು ಎಲ್ಲಾ ಸಾಧ್ಯವಾದ ಕ್ರಮಗಳನ್ನು ಕೈಗೊಳ್ಳುತ್ತದೆ ಮತ್ತು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾ ಯಾವುದೇ ಸಂಸ್ಥೆ ಅಥವಾ ದೇಶಕ್ಕೆ ವರ್ಗಾಯಿಸಲಾಗುವುದಿಲ್ಲ, unless there are adequate controls in place including the security of Your data and other personal information.",
deleteYourData: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾ ಅಳಿಸುವಿಕೆ",
deleteYourDataContent: "ನೀವು ನಮ್ಮ ವ್ಯವಸ್ಥೆಗಳಿಂದ ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸುವಂತೆ ಅಧಿಕೃತವಾಗಿ ವಿನಂತಿಸಬಹುದು.",
howToDeleteData: "ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಅಳಿಸಲು ಹೇಗೆ: 1. ನೀವು ಹೊಂದಿದ್ದರೆ ನಿಮ್ಮ ಖಾತೆಗೆ ಲಾಗಿನ್ ಆಗಿ. 2. ಖಾತೆ ಸೆಟಿಂಗ್‌ಗಳ ವಿಭಾಗಕ್ಕೆ ಹೋಗಿ. 3. ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿಯನ್ನು ನಿರ್ವಹಿಸಲು ಆಯ್ಕೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ. 4. ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಅಳಿಸಲು ಸೂಚನೆಗಳನ್ನು ಅನುಸರಿಸಿ. ನಮ್ಮ ಸೇವೆ ನಿಮಗೆ ಸೇವೆಯ ಒಳಗೆ ನಿಮ್ಮ ಬಗ್ಗೆ ಕೆಲವು ಮಾಹಿತಿಯನ್ನು ಅಳಿಸಲು ಅವಕಾಶ ನೀಡಬಹುದು. ನೀವು ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುವ ಮೂಲಕ ನಿಮ್ಮಿಂದ ಒದಗಿಸಲಾದ ಯಾವುದೇ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿಯ ಪ್ರವೇಶ, ಸರಿಪಡಿಸುವಿಕೆ ಅಥವಾ ಅಳಿಸುವಿಕೆಗಾಗಿ ವಿನಂತಿಸಬಹುದು. ಗಮನಿಸಿ: ನಾವು ಕಾನೂನು ಬದ್ಧತೆಯ ಅಥವಾ ಕಾನೂನಾತ್ಮಕ ಆಧಾರವನ್ನು ಹೊಂದಿದಾಗ ಕೆಲವು ಮಾಹಿತಿಯನ್ನು ಉಳಿಸಲು ಅಗತ್ಯವಿರಬಹುದು.",
disclosureOfData: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾ ಬಹಿರಂಗಪಡಿಸುವಿಕೆ",
businessTransactions: "ವ್ಯವಹಾರ ವ್ಯವಹಾರಗಳು: ಕಂಪನಿಯು ಮರ್ಜರ್, ಅಕ್ವಿಜಿಷನ್ ಅಥವಾ ಆಸ್ತಿ ಮಾರಾಟದಲ್ಲಿ ಭಾಗವಹಿಸಿದರೆ, ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾ ವರ್ಗಾಯಿಸಲಾಗಬಹುದು. ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾ ವರ್ಗಾಯಿತಾದಾಗ ಮತ್ತು ವಿಭಿನ್ನ ಗೌಪ್ಯತಾ ನೀತಿಗೆ ಒಳಗಾಗುವಾಗ, ನಾವು ನಿಮಗೆ ಸೂಚನೆ ನೀಡುತ್ತೇವೆ.",
lawEnforcement: "ಕಾನೂನು ನಿರ್ವಹಣೆ: ಕೆಲವು ಪರಿಸ್ಥಿತಿಗಳಲ್ಲಿ, ಕಂಪನಿಯು ಕಾನೂನಿನ ಆಧಾರದ ಮೇಲೆ ಅಥವಾ ಸಾರ್ವಜನಿಕ ಅಧಿಕಾರಗಳ ಮಾನ್ಯ ವಿನಂತಿಗಳಿಗೆ ಉತ್ತರಿಸಲು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಬಹಿರಂಗಪಡಿಸಲು ಬಾಧ್ಯವಾಗಬಹುದು (ಉದಾಹರಣೆಗೆ, ನ್ಯಾಯಾಲಯ ಅಥವಾ ಸರ್ಕಾರದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲದ ಏಕಕಾಲ",
  otherLegalRequirements: "ಇತರ ಕಾನೂನಾತ್ಮಕ ಅಗತ್ಯಗಳು: ಕಂಪನಿಯು ಉತ್ತಮ ನಂಬಿಕೆಯಲ್ಲಿ ಈ ಕಾರ್ಯವನ್ನು ಕೈಗೊಳ್ಳುವುದು ಅಗತ್ಯವಿದೆ ಎಂದು ನಂಬಿದಾಗ ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಬಹಿರಂಗಪಡಿಸಬಹುದು: ಕಾನೂನು ಬದ್ಧತೆಯನ್ನು ಪಾಲಿಸಲು, ಕಂಪನಿಯ ಹಕ್ಕುಗಳು ಅಥವಾ ಆಸ್ತಿ ರಕ್ಷಿಸಲು ಮತ್ತು ರಕ್ಷಿಸಲು, ಸೇವೆಯ ಬಳಕೆದಾರರ ಅಥವಾ ಸಾರ್ವಜನಿಕರ ವೈಯಕ್ತಿಕ ಸುರಕ್ಷತೆಯನ್ನು ರಕ್ಷಿಸಲು, ಕಾನೂನಾತ್ಮಕ ಹೊಣೆಗಾರಿಕೆಯನ್ನು ತಡೆಯಲು.",
securityOfData: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾ ಭದ್ರತೆ: ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ರಕ್ಷಿಸಲು ಕೈಗೊಳ್ಳುವ ಕೈಗಾರಿಕಾ ಪ್ರಮಾಣಿತ ಕ್ರಮಗಳನ್ನು ನಾವು ಅನುಸರಿಸುತ್ತೇವೆ; ಆದರೆ, ಯಾವುದೇ ಇಲೆಕ್ಟ್ರಾನಿಕ್ ಪ್ರಸರಣ ಅಥವಾ ಸಂಗ್ರಹಣಾ ವ್ಯವಸ್ಥೆ ಸಂಪೂರ್ಣವಾಗಿ ಸುರಕ್ಷಿತವಾಗಿರಲು ಖಾತರಿಯಿಲ್ಲ. ನಾವು ವ್ಯಾಪಾರಿಕವಾಗಿ ಸಮರ್ಥವಾದ ರಕ್ಷಣೆಯನ್ನು ಬಳಸುತ್ತೇವೆ, ಆದರೆ ಸಂಪೂರ್ಣ ಭದ್ರತೆ ಖಾತರಿಯಲ್ಲ.",
paymentsPolicy: "ಪಾವತಿ ನೀತಿ",
paymentProcessing: "ಪಾವತಿ ಪ್ರಕ್ರಿಯೆ: ಎಲ್ಲಾ ಪಾವತಿ ವ್ಯವಹಾರಗಳನ್ನು ಪ್ರಮಾಣಿತ ತೃತೀಯ ಪಕ್ಷದ ಪಾವತಿ ಪ್ರಕ್ರಿಯಕರ ಮೂಲಕ ಸುರಕ್ಷಿತವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತದೆ. ನಾವು ನಿಮ್ಮ ಸಂಪೂರ್ಣ ಪಾವತಿ ಕಾರ್ಡ್ ಅಥವಾ ಬ್ಯಾಂಕಿಂಗ್ ವಿವರಗಳನ್ನು ನಮ್ಮ ವ್ಯವಸ್ಥೆಗಳಲ್ಲಿ ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ, ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ ಅಥವಾ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸುವುದಿಲ್ಲ. ನಿಮ್ಮ ಪಾವತಿ ಮಾಹಿತಿಯನ್ನು ನೇರವಾಗಿ ನಮ್ಮ ಅಧಿಕೃತ ಪಾವತಿ ಪಾಲುದಾರರಿಗೆ ವರ್ಗಾಯಿಸಲಾಗುತ್ತದೆ, PCI-DSS ಮಾನದಂಡಗಳಿಗೆ ಅನುಗುಣವಾಗಿ, ಮತ್ತು ಇದರ ನಿರ್ವಹಣೆ ಸಂಬಂಧಿತ ಪ್ರಕ್ರಿಯಕರ ಗೌಪ್ಯತಾ ಮತ್ತು ಭದ್ರತಾ ನೀತಿಗಳಿಂದ ನಿಯಂತ್ರಿತವಾಗಿರುತ್ತದೆ.",
acceptedPaymentMethods: "ಸ್ವೀಕೃತ ಪಾವತಿ ವಿಧಾನಗಳು: ಕ್ರೆಡಿಟ್ ಮತ್ತು ಡೆಬಿಟ್ ಕಾರ್ಡ್‌ಗಳು, UPI (ಯುನಿಫೈಡ್ ಪೇಮೆಂಟ್ ಇಂಟರ್ಫೇಸ್), ನೆಟ್ ಬ್ಯಾಂಕಿಂಗ್, ವಾಲೆಟ್ಸ್ ಅಥವಾ ಇತರ ಡಿಜಿಟಲ್ ಪಾವತಿ ವಿಧಾನಗಳು. ಈ ವಿಧಾನಗಳ ಲಭ್ಯತೆ ನಿಮ್ಮ ಸ್ಥಳ ಮತ್ತು ಬಳಸುವ ಸೇವೆಯ ಆಧಾರದ ಮೇಲೆ ಬದಲಾಗಬಹುದು.",
paymentSecurity: "ಪಾವತಿ ಭದ್ರತೆ: ಎನ್‌ಕ್ರಿಪ್ಟೆಡ್ ವ್ಯವಹಾರಗಳು (HTTPS, SSL/TLS), PCI-DSS ಅನುಗುಣವಾದ ಪ್ರಕ್ರಿಯಕರ, ಸುರಕ್ಷಿತ ಪಾವತಿ ನಿರ್ವಹಣೆ.",
refundsAndCancellations: "ಹಿಂತೆಗೆದುಕೊಳ್ಳುವಿಕೆ ಮತ್ತು ರದ್ದುಪಡಿಸುವಿಕೆ: ಹಿಂತೆಗೆದುಕೊಳ್ಳುವಿಕೆ ಮತ್ತು ರದ್ದುಪಡಿಸುವಿಕೆ ನೀತಿಗಳು ಖರೀದಿಸಿದ ಸೇವೆ ಅಥವಾ ಉತ್ಪನ್ನಕ್ಕೆ ನಿರ್ದಿಷ್ಟವಾಗಿರುತ್ತವೆ. ದಯವಿಟ್ಟು ನಿರ್ದಿಷ್ಟ ಉತ್ಪನ್ನ ಅಥವಾ ಸೇವಾ ಪುಟವನ್ನು ನೋಡಿ ಅಥವಾ ವಿವರಗಳಿಗಾಗಿ ನಮ್ಮ ಬೆಂಬಲ ತಂಡವನ್ನು ಸಂಪರ್ಕಿಸಿ: ಹಿಂತೆಗೆದುಕೊಳ್ಳುವಿಕೆಗಾಗಿ ಅರ್ಹತೆ, ಹಿಂತೆಗೆದುಕೊಳ್ಳುವಿಕೆ ಪ್ರಕ್ರಿಯೆಗೆ ಸಮಯ, ಹಿಂತೆಗೆದುಕೊಳ್ಳುವಿಕೆಗಾಗಿ ಶರತ್ತುಗಳು.",
billingAndCharges: "ಬಿಲ್ಲಿಂಗ್ ಮತ್ತು ಶುಲ್ಕಗಳು: ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಬಳಸುವ ಮೂಲಕ, ನೀವು ಎಲ್ಲಾ ಅನ್ವಯಿಸುವ ಶುಲ್ಕಗಳು ಮತ್ತು ಶುಲ್ಕಗಳು, ಪಾವತಿ ಪ್ರಕ್ರಿಯಕರಿಂದ ವಿಧಿಸಲಾದ ತೆರಿಗೆಗಳು ಅಥವಾ ಹೆಚ್ಚುವರಿ ವೆಚ್ಚಗಳನ್ನು ಪಾವತಿಸಲು ಒಪ್ಪುತ್ತೀರಿ. ಪಾವತಿಗಳು ನೀಡಲಾದ ಬಿಲ್ಲಿಂಗ್ ಶರತ್ತುಗಳೊಂದಿಗೆ ತಕ್ಷಣವೇ ಪೂರ್ಣಗೊಳ್ಳಬೇಕು. ವಿಫಲ ಪಾವತಿ ಅಥವಾ ಚಾರ್ಜ್‌ಬ್ಯಾಕ್‌ಗಳ ಸಂದರ್ಭದಲ್ಲಿ, ಸಮಸ್ಯೆ ಪರಿಹಾರವಾಗುವವರೆಗೆ ನಿಮ್ಮ ಸೇವೆಗಳಿಗೆ ಪ್ರವೇಶವನ್ನು ನಿಲ್ಲಿಸಲು ಅಥವಾ ಕೊನೆಗೊಳಿಸಲು ನಾವು ಹಕ್ಕು ಹೊಂದಿದ್ದೇವೆ.",
childrensPrivacy: "ಮಕ್ಕಳ ಗೌಪ್ಯತೆ",
importantNotice: "ಮಹತ್ವದ ಸೂಚನೆ: ನಮ್ಮ ಸೇವೆ 13 ವರ್ಷದ ಅಡಿಯಲ್ಲಿ ಯಾರಿಗೂ ಉದ್ದೇಶಿತವಾಗಿಲ್ಲ. ನಾವು 13 ವರ್ಷದ ಅಡಿಯಲ್ಲಿ ಯಾರಿಂದಲೂ ವೈಯಕ್ತಿಕವಾಗಿ ಗುರುತಿಸಬಹುದಾದ ಮಾಹಿತಿಯನ್ನು ತಿಳಿದಿಲ್ಲ. ನೀವು ಪೋಷಕರಾಗಿದ್ದರೆ ಮತ್ತು ನಿಮ್ಮ ಮಗುವು ನಮಗೆ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಒದಗಿಸಿರುವುದನ್ನು ನೀವು ತಿಳಿದಿದ್ದರೆ, ದಯವಿಟ್ಟು ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ. ನಾವು 13 ವರ್ಷದ ಅಡಿಯಲ್ಲಿ ಯಾರಿಂದಲೂ ವೈಯಕ್ತಿಕ ಡೇಟಾವನ್ನು ಸಂಗ್ರಹಿಸಿರುವುದನ್ನು ತಿಳಿದಾಗ, ಪೋಷಕರ ಅನುಮೋದನೆಯ ದೃಢೀಕರಣವಿಲ್ಲದೆ, ನಾವು ಆ ಮಾಹಿತಿಯನ್ನು ನಮ್ಮ ಸ",
  data: "ಮಾಹಿತಿಯನ್ನು ನಮ್ಮ ಸರ್ವರ್‌ಗಳಿಂದ ತೆಗೆದುಹಾಕಲು ಕ್ರಮಗಳನ್ನು ಕೈಗೊಳ್ಳುತ್ತೇವೆ. ನೀವು ನಿಮ್ಮ ಮಗುವಿನ ಮಾಹಿತಿಯನ್ನು ತೆಗೆದುಹಾಕಲು ಬಯಸಿದರೆ, ದಯವಿಟ್ಟು ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ.",
linksToOtherWebsites: "ಇತರ ವೆಬ್‌ಸೈಟ್‌ಗಳಿಗೆ ಲಿಂಕ್ಸ್: ನಮ್ಮ ಸೇವೆಯಲ್ಲಿ ಇತರ ವೆಬ್‌ಸೈಟ್‌ಗಳಿಗೆ ಲಿಂಕ್ಸ್ ಇರಬಹುದು, ಅವುಗಳನ್ನು ನಾವು ನಿರ್ವಹಿಸುತ್ತಿಲ್ಲ. ನೀವು ತೃತೀಯ ಪಕ್ಷದ ಲಿಂಕ್ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿದರೆ, ನೀವು ಆ ತೃತೀಯ ಪಕ್ಷದ ವೆಬ್‌ಸೈಟ್‌ಗೆ yönlendirilirsiniz. ನೀವು ಭೇಟಿ ನೀಡುವ ಪ್ರತಿಯೊಂದು ವೆಬ್‌ಸೈಟ್‌ನ ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ಪರಿಶೀಲಿಸಲು ನಾವು ನಿಮಗೆ ಶಿಫಾರಸು ಮಾಡುತ್ತೇವೆ. ನಾವು ಯಾವುದೇ ತೃತೀಯ ಪಕ್ಷದ ವೆಬ್‌ಸೈಟ್‌ಗಳ ವಿಷಯ, ಗೌಪ್ಯತಾ ನೀತಿಗಳು ಅಥವಾ ಕಾರ್ಯವಿಧಾನಗಳಿಗೆ ನಿಯಂತ್ರಣವಿಲ್ಲ ಮತ್ತು ಹೊಣೆಗಾರಿಕೆಯನ್ನು ಹೊಂದಿಲ್ಲ.",
changesToPolicy: "ಈ ಗೌಪ್ಯತಾ ನೀತಿಯಲ್ಲಿ ಬದಲಾವಣೆಗಳು: ನಾವು ನಮ್ಮ ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ಸಮಯಕ್ಕೆ ಸಮಯಕ್ಕೆ ನವೀಕರಿಸಬಹುದು. ಹೊಸ ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ಈ ಪುಟದಲ್ಲಿ ಪೋಸ್ಟ್ ಮಾಡುವ ಮೂಲಕ ನಾವು ನಿಮಗೆ ಯಾವುದೇ ಬದಲಾವಣೆಗಳ ಬಗ್ಗೆ ತಿಳಿಸುತ್ತೇವೆ. ಸೂಚನೆ: ಬದಲಾವಣೆಗಳು ಪರಿಣಾಮ ಬೀರುವ ಮೊದಲು, ನಾವು ನಿಮಗೆ ಇಮೇಲ್ ಮೂಲಕ ಮತ್ತು/ಅಥವಾ ನಮ್ಮ ಸೇವೆಯಲ್ಲಿ ಪ್ರಮುಖ ಸೂಚನೆಯ ಮೂಲಕ ತಿಳಿಸುತ್ತೇವೆ ಮತ್ತು ಈ ಗೌಪ್ಯತಾ ನೀತಿಯ ಮೇಲ್ಭಾಗದಲ್ಲಿ 'ಕೊನೆಯ ನವೀಕರಣ' ದಿನಾಂಕವನ್ನು ನವೀಕರಿಸುತ್ತೇವೆ. ಈ ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ನಿಯಮಿತವಾಗಿ ಪರಿಶೀಲಿಸಲು ನೀವು ಸಲಹೆ ನೀಡುತ್ತೀರಿ. ಈ ಗೌಪ್ಯತಾ ನೀತಿಯಲ್ಲಿ ಬದಲಾವಣೆಗಳು ಈ ಪುಟದಲ್ಲಿ ಪೋಸ್ಟ್ ಮಾಡಿದಾಗ ಪರಿಣಾಮ ಬೀರುತ್ತವೆ.",
contactUss: "ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ: ನೀವು ಈ ಗೌಪ್ಯತಾ ನೀತಿ ಬಗ್ಗೆ ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳಿದ್ದರೆ, ನೀವು ಈ ಕೆಳಗಿನ ವಿಧಾನಗಳಲ್ಲಿ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಬಹುದು:",
terms: "ಶರತ್ತುಗಳು",
phone: "ದೂರವಾಣಿ: +91 7090007776",
emails: "ಇಮೇಲ್: contact@nandhubus.in",
downloadPolicy: "ನೀತಿ ಡೌನ್‌ಲೋಡ್: PDF ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ",

  },
};

type Language = "en" | "kn";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  // Initialize state with the value from localStorage or default to 'en'
  const [language, setLanguage] = useState<Language>("en");

  // Load language from localStorage when component mounts
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language preference to localStorage whenever it changes
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: keyof typeof translations.en) => translations[language][key];

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage: handleSetLanguage,  // Use our custom setter
      t 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};